# Generated by Django 6.0.1 on 2026-04-01 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OutdoorShop', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
