# Generated by Django 6.0.1 on 2026-04-05 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OutdoorShop', '0003_popular_search_term'),
        ('OutdoorShop', '0003_popularsearchterm'),
    ]

    operations = [
    ]
