# Generated by Django 6.0.1 on 2026-04-02 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_shippingaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='street_address',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='barangay',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='province',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='address_line_1',
            field=models.CharField(default='N/A', help_text='Street address, P.O. box, company name, c/o', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='address_line_2',
            field=models.CharField(blank=True, help_text='Apartment, suite, unit, building, floor, etc.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='country',
            field=models.CharField(default='Philippines', max_length=100),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Set as default shipping address'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='phone_number',
            field=models.CharField(default='N/A', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='postal_code',
            field=models.CharField(default='N/A', max_length=20, verbose_name='ZIP/Postal Code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='state',
            field=models.CharField(default='N/A', max_length=100, verbose_name='State/Province/Region'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='address_type',
            field=models.CharField(blank=True, help_text='e.g., Home, Office', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_addresses', to=settings.AUTH_USER_MODEL),
        ),
    ]
