# Generated by Django 6.0.1 on 2026-04-02 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_street_address_shippingaddress_full_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='last_name',
            field=models.CharField(default='User', max_length=255),
            preserve_default=False,
        ),
    ]
