# Generated by Django 6.0.1 on 2026-03-23 05:15

import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_sizeguide_listing_size_guide'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingvariant',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=inventory.models.generate_image_path),
        ),
    ]
