# Generated by Django 6.0.1 on 2026-03-23 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_activity_listing_ativity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='ativity',
            new_name='activity',
        ),
    ]
