# Generated by Django 6.0.1 on 2026-03-07 21:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_productattribute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingvariant',
            name='current_stock_quantity',
        ),
        migrations.RemoveField(
            model_name='listingvariant',
            name='variant_name',
        ),
        migrations.AddField(
            model_name='listingvariant',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listingvariant',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='listingvariant',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listingvariant',
            name='status',
            field=models.CharField(choices=[('in_stock', 'In Stock'), ('out_of_stock', 'Out of Stock'), ('discontinued', 'Discontinued'), ('damaged', 'Damaged/Hold')], default='in_stock', max_length=20),
        ),
    ]
