# Generated by Django 6.0.1 on 2026-03-07 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_listingvariant_current_stock_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listingvariant',
            old_name='quantity',
            new_name='current_stock_quantity',
        ),
        migrations.AddField(
            model_name='listingvariant',
            name='variant_name',
            field=models.CharField(default='Standard', max_length=255),
        ),
    ]
