# Generated by Django 6.0.1 on 2026-03-23 10:17

import django.db.models.deletion
import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_rename_ativity_listing_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(upload_to=inventory.models.generate_image_path)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='inventory.listing')),
            ],
        ),
    ]
