# Generated by Django 6.0.1 on 2026-04-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_activity_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='variant',
        ),
        migrations.AddField(
            model_name='listing',
            name='gender',
            field=models.CharField(choices=[('unisex', 'Unisex'), ('mens', "Men's"), ('womens', "Women's"), ('kids', 'Kids')], default='unisex', help_text='Target gender for this product', max_length=10),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
