# Generated by Django 6.0.1 on 2026-03-08 16:11

import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_stockledger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingimage',
            name='image_file',
            field=models.ImageField(upload_to=inventory.models.variant_image_path),
        ),
    ]
