# Generated by Django 6.0.1 on 2026-03-07 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitem',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='POSSale',
        ),
        migrations.DeleteModel(
            name='SaleItem',
        ),
    ]
